export { default as facebookIcon } from '@/assets/icons/social/facebook.svg'
export { default as instagramIcon } from '@/assets/icons/social/instagram.svg'
export { default as okIcon } from '@/assets/icons/social/ok.svg'
export { default as telegramIcon } from '@/assets/icons/social/telegram.svg'
export { default as tikTokIcon } from '@/assets/icons/social/tik_tok.svg'
export { default as twitterIcon } from '@/assets/icons/social/twitter.svg'
export { default as vkIcon } from '@/assets/icons/social/vk.svg'